server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankservices
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always   # runs schema/data scripts at startup

  redis:
    host: localhost
    port: 6379