server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/bankservices
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always   # runs schema/data scripts at startup

  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    hostname: account-service
    prefer-ip-address: false
